# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sakeplot.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SAKEDSP(object):
    def setupUi(self, SAKEDSP):
        SAKEDSP.setObjectName("SAKEDSP")
        SAKEDSP.resize(327, 270)
        self.centralwidget = QtWidgets.QWidget(SAKEDSP)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.PSDEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PSDEdit.setFont(font)
        self.PSDEdit.setFrame(True)
        self.PSDEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.PSDEdit.setObjectName("PSDEdit")
        self.gridLayout.addWidget(self.PSDEdit, 3, 2, 1, 2)
        self.pathEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pathEdit.setFont(font)
        self.pathEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pathEdit.setReadOnly(True)
        self.pathEdit.setObjectName("pathEdit")
        self.gridLayout.addWidget(self.pathEdit, 0, 0, 1, 4)
        self.verifyButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.verifyButton.setFont(font)
        self.verifyButton.setObjectName("verifyButton")
        self.gridLayout.addWidget(self.verifyButton, 2, 4, 1, 1)
        self.PSDButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PSDButton.setFont(font)
        self.PSDButton.setObjectName("PSDButton")
        self.gridLayout.addWidget(self.PSDButton, 3, 4, 1, 1)
        self.labelPoweAreaRange = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelPoweAreaRange.setFont(font)
        self.labelPoweAreaRange.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPoweAreaRange.setObjectName("labelPoweAreaRange")
        self.gridLayout.addWidget(self.labelPoweAreaRange, 4, 0, 1, 1)
        self.PoweAreaNumeratorEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PoweAreaNumeratorEdit.setFont(font)
        self.PoweAreaNumeratorEdit.setFrame(True)
        self.PoweAreaNumeratorEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.PoweAreaNumeratorEdit.setObjectName("PoweAreaNumeratorEdit")
        self.gridLayout.addWidget(self.PoweAreaNumeratorEdit, 4, 1, 1, 1)
        self.labelPlotType_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelPlotType_2.setFont(font)
        self.labelPlotType_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPlotType_2.setObjectName("labelPlotType_2")
        self.gridLayout.addWidget(self.labelPlotType_2, 4, 2, 1, 1)
        self.PoweAreaDenomenatorEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PoweAreaDenomenatorEdit.setFont(font)
        self.PoweAreaDenomenatorEdit.setFrame(True)
        self.PoweAreaDenomenatorEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.PoweAreaDenomenatorEdit.setObjectName("PoweAreaDenomenatorEdit")
        self.gridLayout.addWidget(self.PoweAreaDenomenatorEdit, 4, 3, 1, 1)
        self.labelPlotType = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelPlotType.setFont(font)
        self.labelPlotType.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPlotType.setObjectName("labelPlotType")
        self.gridLayout.addWidget(self.labelPlotType, 5, 0, 1, 1)
        self.threshEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.threshEdit.setFont(font)
        self.threshEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.threshEdit.setObjectName("threshEdit")
        self.gridLayout.addWidget(self.threshEdit, 2, 2, 1, 2)
        self.pathButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pathButton.setFont(font)
        self.pathButton.setObjectName("pathButton")
        self.gridLayout.addWidget(self.pathButton, 0, 4, 1, 1)
        self.plotType = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plotType.setFont(font)
        self.plotType.setObjectName("plotType")
        self.gridLayout.addWidget(self.plotType, 5, 1, 1, 3)
        self.PowerAreaButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PowerAreaButton.setFont(font)
        self.PowerAreaButton.setObjectName("PowerAreaButton")
        self.gridLayout.addWidget(self.PowerAreaButton, 4, 4, 1, 1)
        self.labelPSDRange = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelPSDRange.setFont(font)
        self.labelPSDRange.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPSDRange.setObjectName("labelPSDRange")
        self.gridLayout.addWidget(self.labelPSDRange, 3, 0, 1, 1)
        self.errorBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.errorBrowser.setFont(font)
        self.errorBrowser.setObjectName("errorBrowser")
        self.gridLayout.addWidget(self.errorBrowser, 6, 0, 1, 5)
        self.labelThresh = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelThresh.setFont(font)
        self.labelThresh.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelThresh.setObjectName("labelThresh")
        self.gridLayout.addWidget(self.labelThresh, 2, 0, 1, 1)
        self.STFTButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.STFTButton.setFont(font)
        self.STFTButton.setObjectName("STFTButton")
        self.gridLayout.addWidget(self.STFTButton, 1, 0, 1, 5)
        SAKEDSP.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SAKEDSP)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 327, 18))
        self.menubar.setObjectName("menubar")
        SAKEDSP.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SAKEDSP)
        self.statusbar.setObjectName("statusbar")
        SAKEDSP.setStatusBar(self.statusbar)

        self.retranslateUi(SAKEDSP)
        QtCore.QMetaObject.connectSlotsByName(SAKEDSP)

    def retranslateUi(self, SAKEDSP):
        _translate = QtCore.QCoreApplication.translate
        SAKEDSP.setWindowTitle(_translate("SAKEDSP", "SAKE Plot"))
        self.PSDEdit.setText(_translate("SAKEDSP", "1-30"))
        self.verifyButton.setText(_translate("SAKEDSP", "Verify"))
        self.PSDButton.setText(_translate("SAKEDSP", "Plot PSD"))
        self.labelPoweAreaRange.setText(_translate("SAKEDSP", "Power Area Range (hz):"))
        self.PoweAreaNumeratorEdit.setText(_translate("SAKEDSP", "1-30"))
        self.labelPlotType_2.setText(_translate("SAKEDSP", "/"))
        self.PoweAreaDenomenatorEdit.setText(_translate("SAKEDSP", "none"))
        self.labelPlotType.setText(_translate("SAKEDSP", "Plot Type:"))
        self.threshEdit.setText(_translate("SAKEDSP", "3"))
        self.pathButton.setText(_translate("SAKEDSP", "Set Path..."))
        self.PowerAreaButton.setText(_translate("SAKEDSP", "Plot Power"))
        self.labelPSDRange.setText(_translate("SAKEDSP", "PSD Range (hz):"))
        self.labelThresh.setText(_translate("SAKEDSP", "Outlier Threshold:"))
        self.STFTButton.setText(_translate("SAKEDSP", "Fourier Transform (STFT)"))

