# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sakeplot.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SAKEDSP(object):
    def setupUi(self, SAKEDSP):
        SAKEDSP.setObjectName("SAKEDSP")
        SAKEDSP.resize(621, 448)
        self.centralwidget = QtWidgets.QWidget(SAKEDSP)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 1, 1, 1)
        self.pathEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pathEdit.setFont(font)
        self.pathEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pathEdit.setReadOnly(True)
        self.pathEdit.setObjectName("pathEdit")
        self.gridLayout.addWidget(self.pathEdit, 0, 1, 1, 3)
        self.errorBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.errorBrowser.setFont(font)
        self.errorBrowser.setObjectName("errorBrowser")
        self.gridLayout.addWidget(self.errorBrowser, 7, 1, 1, 4)
        self.STFTButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.STFTButton.setFont(font)
        self.STFTButton.setObjectName("STFTButton")
        self.gridLayout.addWidget(self.STFTButton, 1, 1, 1, 4)
        self.plotValue = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plotValue.setFont(font)
        self.plotValue.setObjectName("plotValue")
        self.gridLayout.addWidget(self.plotValue, 4, 2, 1, 1)
        self.PSDButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PSDButton.setFont(font)
        self.PSDButton.setObjectName("PSDButton")
        self.gridLayout.addWidget(self.PSDButton, 3, 4, 1, 1)
        self.labelPlotType = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelPlotType.setFont(font)
        self.labelPlotType.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPlotType.setObjectName("labelPlotType")
        self.gridLayout.addWidget(self.labelPlotType, 4, 1, 1, 1)
        self.plotType = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plotType.setFont(font)
        self.plotType.setObjectName("plotType")
        self.gridLayout.addWidget(self.plotType, 4, 3, 1, 1)
        self.PowerAreaButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PowerAreaButton.setFont(font)
        self.PowerAreaButton.setObjectName("PowerAreaButton")
        self.gridLayout.addWidget(self.PowerAreaButton, 4, 4, 1, 1)
        self.picLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picLabel.sizePolicy().hasHeightForWidth())
        self.picLabel.setSizePolicy(sizePolicy)
        self.picLabel.setMinimumSize(QtCore.QSize(300, 400))
        self.picLabel.setText("")
        self.picLabel.setObjectName("picLabel")
        self.gridLayout.addWidget(self.picLabel, 0, 0, 8, 1)
        self.pathButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pathButton.setFont(font)
        self.pathButton.setObjectName("pathButton")
        self.gridLayout.addWidget(self.pathButton, 0, 4, 1, 1)
        self.verifyButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.verifyButton.setFont(font)
        self.verifyButton.setObjectName("verifyButton")
        self.gridLayout.addWidget(self.verifyButton, 2, 4, 1, 1)
        self.threshEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.threshEdit.setFont(font)
        self.threshEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.threshEdit.setObjectName("threshEdit")
        self.gridLayout.addWidget(self.threshEdit, 2, 2, 1, 1)
        self.reverifyButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reverifyButton.setFont(font)
        self.reverifyButton.setObjectName("reverifyButton")
        self.gridLayout.addWidget(self.reverifyButton, 2, 3, 1, 1)
        self.labelThresh = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelThresh.setFont(font)
        self.labelThresh.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelThresh.setObjectName("labelThresh")
        self.gridLayout.addWidget(self.labelThresh, 2, 1, 1, 1)
        self.PSDEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PSDEdit.setFont(font)
        self.PSDEdit.setFrame(True)
        self.PSDEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.PSDEdit.setObjectName("PSDEdit")
        self.gridLayout.addWidget(self.PSDEdit, 3, 2, 1, 2)
        self.labelPSDRange = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelPSDRange.setFont(font)
        self.labelPSDRange.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPSDRange.setObjectName("labelPSDRange")
        self.gridLayout.addWidget(self.labelPSDRange, 3, 1, 1, 1)
        self.distButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.distButton.setFont(font)
        self.distButton.setObjectName("distButton")
        self.gridLayout.addWidget(self.distButton, 5, 4, 1, 1)
        self.labelDist = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelDist.setFont(font)
        self.labelDist.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelDist.setObjectName("labelDist")
        self.gridLayout.addWidget(self.labelDist, 5, 1, 1, 1)
        self.distEdit = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.distEdit.setFont(font)
        self.distEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.distEdit.setObjectName("distEdit")
        self.gridLayout.addWidget(self.distEdit, 5, 2, 1, 2)
        SAKEDSP.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SAKEDSP)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 621, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        SAKEDSP.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SAKEDSP)
        self.statusbar.setObjectName("statusbar")
        SAKEDSP.setStatusBar(self.statusbar)
        self.actionSettings = QtWidgets.QAction(SAKEDSP)
        self.actionSettings.setObjectName("actionSettings")
        self.menuFile.addAction(self.actionSettings)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(SAKEDSP)
        QtCore.QMetaObject.connectSlotsByName(SAKEDSP)

    def retranslateUi(self, SAKEDSP):
        _translate = QtCore.QCoreApplication.translate
        SAKEDSP.setWindowTitle(_translate("SAKEDSP", "SAKE Plot"))
        self.label.setText(_translate("SAKEDSP", "Notifications:"))
        self.STFTButton.setText(_translate("SAKEDSP", "Fourier Transform (STFT)"))
        self.PSDButton.setText(_translate("SAKEDSP", "Plot PSD"))
        self.labelPlotType.setText(_translate("SAKEDSP", "Power Area Type:"))
        self.PowerAreaButton.setText(_translate("SAKEDSP", "Plot Power"))
        self.pathButton.setText(_translate("SAKEDSP", "Set Path..."))
        self.verifyButton.setText(_translate("SAKEDSP", "Verify"))
        self.threshEdit.setText(_translate("SAKEDSP", "4"))
        self.reverifyButton.setText(_translate("SAKEDSP", "Reverify"))
        self.labelThresh.setText(_translate("SAKEDSP", "Outlier Threshold:"))
        self.PSDEdit.setText(_translate("SAKEDSP", "1-30"))
        self.labelPSDRange.setText(_translate("SAKEDSP", "PSD Range (hz):"))
        self.distButton.setText(_translate("SAKEDSP", "Plot Dist"))
        self.labelDist.setText(_translate("SAKEDSP", "Distribution Range:"))
        self.distEdit.setText(_translate("SAKEDSP", "40-70"))
        self.menuFile.setTitle(_translate("SAKEDSP", "File"))
        self.actionSettings.setText(_translate("SAKEDSP", "Settings"))

