fft_freq_range:
- 1
- 150
fft_win: 5
file_index: file_index.csv
file_index_verified: file_index_verified.csv
file_power_mat: power_mat.pickle
file_power_mat_verified: power_mat_verified.pickle
freq_ranges:
- - 2
  - 5
- - 6
  - 12
- - 15
  - 29
- - 30
  - 70
- - 80
  - 120
freq_ratios:
- - - 2
    - 5
  - - 6
    - 12
- - - 15
    - 30
  - - 40
    - 70
mains_noise:
- 59
- 61
melted_power_mat: power_area.csv
search_path: C:\Users\panton01\Desktop\pydsp_analysis
summary_plot_type: violin
