exclude_categories:
- cat1
- cat2
fft_freq_range:
- 1
- 150
fft_overlap: 0.5
fft_win: 5
file_index: index.csv
file_index_verified: index_verified.csv
file_power_mat: power_mat.pickle
file_power_mat_verified: power_mat_verified.pickle
freq_ranges:
- - 2
  - 5
- - 6
  - 12
- - 15
  - 30
- - 40
  - 70
- - 80
  - 120
freq_ratios:
- - - 2
    - 5
  - - 6
    - 12
- - - 15
    - 30
  - - 40
    - 70
index_present: 1
mains_noise:
- 59
- 61
norm_groups:
- sex
- male
normalize: 0
outlier_threshold: 7
outlier_window: 60
power_area_mat: power_area.csv
power_present: 1
power_verified_present: 1
psd_mat: psd.csv
search_path:
summary_plot_type: violin
