# parent path to search for file_index and power_mat
search_path: 'C:\Users\panton01\Desktop\pydsp_analysis'

# file containing experiment index
file_index: 'file_index.csv'

# converted frequency spectrum
power_mat: 'power_mat.pickle'

# frequency range for convertion (STFT) 
fft_freq:
-1
-150

# frequency band for removing mains noise
mains_noise:
-59
-61

# frequency ranges for plotting and export
freq_ranges:
- - 2
  - 5
- - 6
  - 12
- - 15
  - 29
- - 30
  - 70
- - 80
  - 120





