fft_freq_range:
- 1
- 150
fft_win: 5
file_index: file_index.csv
file_power_mat: power_mat.pickle
melted_power_mat: melted_power_area.csv
freq_ranges:
- - 2
  - 5
- - 6
  - 12
- - 15
  - 29
- - 30
  - 70
- - 80
  - 120
mains_noise:
- 59
- 61
search_path: C:\Users\panton01\Desktop\pydsp_analysis
